name: flutter_screen_recording_web
description: Web platform implementation of flutter_screen_recording
version: 1.0.2
homepage: "https://github.com/Isvisoft/flutter_screen_recording"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2
  platform_detect: ^1.4.0
  plugin_platform_interface: ^2.0.2
  meta: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebFlutterScreenRecording
        fileName: flutter_screen_recording_web.dart
